server:
  port: 8080

selmag:
  services:
    catalogue:
      registration-id: keycloak
      uri: http://localhost:8081

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: H4PuvAVFg8cQhbgfIHXtuhVIMwuZoT5c
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt