server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: admin
    password: admin
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
logging:
  level:
    sql: info